Numpy

In [ ]:
import numpy as np  #np is the alias name

In [ ]:
my_list=[2,3,4,5,6]

In [ ]:
print(my_list)

[2, 3, 4, 5, 6]


In [ ]:
type(my_list)

list

In [ ]:
arr=np.array(my_list)  # np.array converts any list into array

In [ ]:
print(arr)

[2 3 4 5 6]


In [ ]:
type(arr)  #ndimentionalarray,n=1 i.e 1D array

numpy.ndarray

In [ ]:
# Multinested array
my_list=[2,3,4,5,6]
my_list_2=[4,5,6,9,3]
my_list_3=[1,7,4,5,6]

In [ ]:
arr_new=np.array([my_list,my_list_2,my_list_3])

In [ ]:
print(arr_new)

[[2 3 4 5 6]
 [4 5 6 9 3]
 [1 7 4 5 6]]


In [ ]:
type(arr_new)

numpy.ndarray

In [ ]:
arr_new.shape  #shows the number of rows and columns in the array

(3, 5)

In [ ]:
type(arr_new)  #=2, 2D array

numpy.ndarray

In [ ]:
arr_new.reshape(5,3)

array([[2, 3, 4],
       [5, 6, 4],
       [5, 6, 9],
       [3, 1, 7],
       [4, 5, 6]])

In [ ]:
print(arr_new.reshape(5,3))

[[2 3 4]
 [5 6 4]
 [5 6 9]
 [3 1 7]
 [4 5 6]]


In [ ]:
arr_new.shape  #shows the number of rows and column in the array

(3, 5)


Indexing and slicing

In [ ]:
print(arr)

[2 3 4 5 6]


In [ ]:
arr[2]

4

In [ ]:
arr[4]

6

In [ ]:
arr[1:4]

array([3, 4, 5])

In [ ]:
print(arr_new)

[[2 3 4 5 6]
 [4 5 6 9 3]
 [1 7 4 5 6]]


In [ ]:
arr_new[1:,3:]   #1: is applicable for rows and 3: is applicable for columns slicing

array([[9, 3],
       [5, 6]])

In [ ]:
arr_new[1:2,2:4]   # 1:2 for row and 2:4 for column

array([[6, 9]])