How to represent Multidimensional Array


In [ ]:
# 1D Array

import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D Array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 3D Array
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


How to create Array

In [ ]:
#How to create Array
Array_1D=np.array([1,2,3,4,5])
print(Array_1D)

[1 2 3 4 5]


In [ ]:
#Find array dimensio
Array_1D.ndim

1

In [ ]:
#Find array type
print(type(Array_1D))

<class 'numpy.ndarray'>


In [ ]:
#Find array shape
Array_1D.shape

(5,)

In [ ]:
#find size of array elements
Array_1D.size

5

In [ ]:
a=np.array([[[1,2,3,4],[10,20,30,40]],[[5,6,7,8],[50,60,70,80]]])
print(a)

[[[ 1  2  3  4]
  [10 20 30 40]]

 [[ 5  6  7  8]
  [50 60 70 80]]]


In [ ]:
a.size

16

In [ ]:
a.shape

(2, 2, 4)

In [ ]:
Array_1D.dtype

dtype('int64')

In [ ]:
#create 2D array
a=np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


In [ ]:
a.ndim

2

In [ ]:
a.size

12

In [ ]:
a.shape

(3, 4)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
#create 3D array
a=np.array([[[1,2,3,4],[10,20,30,40]],[[5,6,7,8],[50,60,70,80]],[[11,12,13,14],[15,16,17,18]]])
print(a)

[[[ 1  2  3  4]
  [10 20 30 40]]

 [[ 5  6  7  8]
  [50 60 70 80]]

 [[11 12 13 14]
  [15 16 17 18]]]


In [ ]:
a.ndim

3

In [ ]:
a.size

24

In [ ]:
a.shape

(3, 2, 4)

In [ ]:
#create once matrix
ones=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
ones=np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [ ]:
ones.ndim

1

In [ ]:
ones.shape

(5,)

In [ ]:
ones.dtype

dtype('float64')

In [ ]:
#2D ones matrix
array_2d=np.ones((2,3), dtype='int')

In [ ]:
print(array_2d)

[[1 1 1]
 [1 1 1]]


In [ ]:
array_2d=np.ones((3,2,4), dtype='str')
print(array_2d)

[[['1' '1' '1' '1']
  ['1' '1' '1' '1']]

 [['1' '1' '1' '1']
  ['1' '1' '1' '1']]

 [['1' '1' '1' '1']
  ['1' '1' '1' '1']]]


In [ ]:
#create zero matrix
zeros_mx=np.zeros((2,3,4), dtype='str')
print(zeros_mx)

[[['' '' '' '']
  ['' '' '' '']
  ['' '' '' '']]

 [['' '' '' '']
  ['' '' '' '']
  ['' '' '' '']]]


In [ ]:
zeros_mx=np.zeros((2,3,4), dtype='int')
print(zeros_mx)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
zeros_mx=np.zeros((2,3,4), dtype='bool')
print(zeros_mx)

[[[False False False False]
  [False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]
  [False False False False]]]


Arange function

In [ ]:
#syntax=np,arange([start,] stop[, step,], dtype=None)
Range=np.arange(0,6).reshape(3,2)
print(Range)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
Range=np.arange(2,21,2).reshape(5,2)
print(Range)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


Linspace

In [ ]:
#syntax: np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=none,axis=0)
Linespace=np.linspace(1,10,10, endpoint=True, retstep=True,axis=0)
print(Linespace)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


In [ ]:
Linesp=np.linspace(1,10,10,endpoint=True)
print(Linesp)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
Linesp=np.linspace(1,10,10, endpoint=True,retstep=True)
print(Linesp)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


Reshape

In [ ]:
#syntax=np.reshape(a, newshape)
array_1d=np.array([1,2,3,4,5,6,7,8])
print(array_1d)

[1 2 3 4 5 6 7 8]


In [ ]:
reshape_2d=array_1d.reshape(2,2,2)
print(reshape_2d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
reshape_3d=array_1d.reshape(1,8,1)  #for 1 layer
print(reshape_3d)

[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]


In [ ]:
reshape3d=array_1d.reshape(2,1,4)
print(reshape3d)

[[[1 2 3 4]]

 [[5 6 7 8]]]


In [ ]:
#use arange function with reshape or viceversa

Reshape1=np.arange(1,10).reshape(3,3)
print(Reshape1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:

reshape1=np.arange(1,10).reshape(1,3,3)
print(reshape1)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:

reshape=np.arange(1,28).reshape(3,3,3)
print(reshape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


Ravel()

In [ ]:
reshape

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
#convert multidimensional array into 1d array
reshape.ravel(order='A')  #order must be one of 'C', 'F', 'A', or 'K'

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [ ]:
#flatten()
reshape.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [ ]:
reshape.flatten(order='c')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [ ]:
reshape.flatten(order='f')

array([ 1, 10, 19,  4, 13, 22,  7, 16, 25,  2, 11, 20,  5, 14, 23,  8, 17,
       26,  3, 12, 21,  6, 15, 24,  9, 18, 27])

In [ ]:
reshape

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
#transpose
#convert rows into columns and vice versa
reshape.transpose()

array([[[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]],

       [[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]]])

In [ ]:
reshape.T

array([[[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]],

       [[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]]])

3. Numpy operation

In [ ]:
array1=np.arange(1,13).reshape(4,3)
array1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
array2=np.arange(1,13).reshape(4,3)
array2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#addition
array1+array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [ ]:
#add
np.add(array1,array2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [ ]:
#subtract
np.subtract(array1,array2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
#multiply
np.multiply(array1,array2)

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [ ]:
#divide
np.divide(array1,array2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

matrix product


In [ ]:
#addition of column and rows
ar1=np.arange(1,10).reshape(3,3)
ar2=np.arange(1,10).reshape(3,3)
print(ar1)
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
1+2+3+4+5+6+7+8+9

45

In [ ]:
ar1.dot(ar2)   #1*1+2*4+3*7=30, 1*2+2*5+3*8=36


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
#max()
ar1.max()

9

In [ ]:
#argmax= find the index of the max value
ar1.argmax()

8

In [ ]:
aa=np.random.randint(1,10,9).reshape(3,3)
print(aa)

[[8 7 7]
 [2 8 4]
 [3 8 8]]


In [ ]:
aa.max(),aa.argmax()

(8, 0)

In [ ]:
#find max value in column and rows using axis parameter
#0 represents columns and 1 represents rows
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar1.max(axis=1)   #max in rows

array([3, 6, 9])

In [ ]:
ar1.max(axis=0)# max in columns

array([7, 8, 9])

In [ ]:
#min and argmin
ar1.min()

1

In [ ]:
ar1.argmin()

0

In [ ]:
#sum
#syntax=np.sum(a,axis=none,dtype=none)
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar1.sum()

45

In [ ]:
a=np.sum(ar1,axis=0)
a

array([12, 15, 18])

In [ ]:
a=np.sum(ar1,axis=1)
a

array([ 6, 15, 24])

In [ ]:
# Mean
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#addition of all element and divide by number of elements
ar1.mean()

5.0

In [ ]:
#sqrt and square
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
np.square(ar1)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
#standard deviation
np.std(ar1)

2.581988897471611

In [ ]:
#exponent
np.exp(ar1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [ ]:
#log() and logbase10=log10

np.log(ar1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [ ]:
np.log10(ar1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

4 Array slicing in Numpy


In [ ]:
mx=np.arange(1,26).reshape(5,5)
mx


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#print 1 element -1D
mx[0,0]

1

In [ ]:
#check dimension
mx[0,0].ndim

0

In [ ]:
#single rows -2D
mx[0:1,0:6]

array([[1, 2, 3, 4, 5]])

In [ ]:
#single column
mx[0:6,0:1]